name: YASH-Traffix-POC/eShopOnWeb_Sonar
on:
  push:
    branches:
    - main
env:
  BuildConfiguration: Release    
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    # The dotnet CLI does not accept glob patterns. Consider using a solution file to act on multiple projects at once.
    - name: dotnet restore
      run: dotnet restore src/ApplicationCore/ApplicationCore.csproj
    # The dotnet CLI does not accept glob patterns. Consider using a solution file to act on multiple projects at once.
    - name: dotnet build
      run: dotnet build **/*.csproj --configuration ${{ env.BuildConfiguration }}
    - name: dotnet publish
      run: dotnet publish --configuration ${{ env.BuildConfiguration }} --output ${{ runner.temp }}
    - name: 'Publish Artifact: drop'
      uses: actions/upload-artifact@v4.1.0
      with:
        name: drop--${{ github.run_id }}-${{ github.run_number }}
        path: "${{ runner.temp }}/artifact"
