name: migrate/eShopOnWeb.git

on:
  push:
    branches:
    - main
env:
  BuildConfiguration: Release    
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    # The dotnet CLI does not accept glob patterns. Consider using a solution file to act on multiple projects at once.
    - name: dotnet restore
      run: dotnet restore **/*.csproj
    # The dotnet CLI does not accept glob patterns. Consider using a solution file to act on multiple projects at once.
    - name: dotnet build
      run: dotnet build **/*.csproj --configuration ${{ env.BuildConfiguration }}
    - name: dotnet publish
      run: dotnet publish --configuration ${{ env.BuildConfiguration }} --output ${{ runner.temp }}
    - name: List Published Files
      run: dir ${{ runner.temp }}\artifact
      
    - name: 'Publish Artifact: drop'
      uses: actions/upload-artifact@v4.1.0
      with:
        name: drop--${{ github.run_id }}-${{ github.run_number }}
        path: ${{ runner.temp }}/artifact
    # - name: List Published Files
    #     run: dir ${{ runner.temp }}\artifact
  
    #   - name: 'Publish Artifact: drop'
    #     uses: actions/upload-artifact@v4.1.0
    #     with:
    #       name: migrate/eShopOnWeb.git
    #       path: ${{ runner.temp }}/artifact
